---
name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a4309e950c75c8fa2b10c969f8238f1d # v6.3.0
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm install

      - name: Lint HTML
        run: npm run lint-html

      - name: Lint JavaScript
        run: npm run lint-js
